let users = [];
let tasks = [];
let editingId = null;
let toastTimer;
const sessionUser = () => JSON.parse(sessionStorage.getItem('fluxo_user') || 'null');
const request = async (url, options = {}) => { const response = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Não foi possível concluir a operação.'); return data; };
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const showToast = (message, isError = false) => { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.toggle('error', isError); toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); };
const handleError = error => showToast(error.message, true);

function switchView(view) { document.querySelectorAll('.view').forEach(item => item.classList.remove('active-view')); document.getElementById(`${view}-view`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); const names = { board: 'Visão geral', 'task-form': 'Nova tarefa', 'user-form': 'Usuários' }; document.getElementById('page-name').textContent = names[view]; if (view === 'task-form') populateUserSelect(); if (view === 'user-form') renderUsers(); }
function populateUserSelect() { const select = document.getElementById('task-user'); const current = select.value; select.innerHTML = '<option value="">Selecione um usuário</option>' + users.map(user => `<option value="${user.id}">${escapeHtml(user.nome)}</option>`).join(''); if (current) select.value = current; }
function renderTask(task) { const priority = { baixa: 'Baixa', media: 'Média', alta: 'Alta' }[task.priority]; return `<article class="task-card"><h4>${escapeHtml(task.description)}</h4><div class="task-meta"><span class="task-sector"><span>⌂</span>${escapeHtml(task.sector)}</span><span class="priority priority-${task.priority}">${priority}</span></div><div class="task-bottom"><span class="task-owner">♙ ${escapeHtml(task.user.nome)}</span><div class="task-actions"><select class="status-select" data-status-id="${task.id}" aria-label="Alterar status"><option value="a fazer" ${task.status === 'a fazer' ? 'selected' : ''}>A fazer</option><option value="fazendo" ${task.status === 'fazendo' ? 'selected' : ''}>Fazendo</option><option value="pronto" ${task.status === 'pronto' ? 'selected' : ''}>Pronto</option></select><button data-action="update-status" data-id="${task.id}" title="Atualizar status">↻</button><button data-action="edit" data-id="${task.id}" title="Editar tarefa">✎</button><button data-action="delete" data-id="${task.id}" title="Excluir tarefa">×</button></div></div></article>`; }
function renderBoard() { const query = document.getElementById('search-input').value.toLowerCase(); const sector = document.getElementById('sector-filter').value; const filtered = tasks.filter(task => (!query || `${task.description} ${task.sector} ${task.user.nome}`.toLowerCase().includes(query)) && (sector === 'all' || task.sector === sector)); const lists = { 'a fazer': document.getElementById('todo-list'), fazendo: document.getElementById('doing-list'), pronto: document.getElementById('done-list') }; Object.entries(lists).forEach(([status, list]) => { const matches = filtered.filter(task => task.status === status); list.innerHTML = matches.length ? matches.map(renderTask).join('') : '<div class="empty-state">Nenhuma tarefa aqui</div>'; document.getElementById(status === 'a fazer' ? 'todo-count' : status === 'fazendo' ? 'doing-count' : 'done-column-count').textContent = matches.length; }); document.getElementById('total-count').textContent = tasks.length; document.getElementById('progress-count').textContent = tasks.filter(task => task.status === 'fazendo').length; document.getElementById('done-count').textContent = tasks.filter(task => task.status === 'pronto').length; document.getElementById('user-count').textContent = users.length; const filter = document.getElementById('sector-filter'); const current = filter.value; filter.innerHTML = '<option value="all">Todos os setores</option>' + [...new Set(tasks.map(task => task.sector))].sort().map(item => `<option>${escapeHtml(item)}</option>`).join(''); filter.value = [...filter.options].some(option => option.value === current) ? current : 'all'; }
function renderUsers() { document.getElementById('user-list').innerHTML = users.length ? users.map(user => `<div class="user-row"><strong>${escapeHtml(user.nome)}</strong><span>${escapeHtml(user.email)}</span></div>`).join('') : '<div class="empty-state">Nenhum usuário cadastrado.</div>'; }
function resetTaskForm() { editingId = null; document.getElementById('task-form').reset(); document.getElementById('task-form-title').textContent = 'Cadastrar tarefa'; }
function editTask(id) { const task = tasks.find(item => item.id === id); if (!task) return; editingId = id; document.getElementById('task-description').value = task.description; document.getElementById('task-sector').value = task.sector; document.getElementById('task-priority').value = task.priority; document.getElementById('task-status').value = task.status; populateUserSelect(); document.getElementById('task-user').value = task.userId; document.getElementById('task-form-title').textContent = 'Editar tarefa'; switchView('task-form'); }
async function loadData() { [users, tasks] = await Promise.all([request('/api/users'), request('/api/tasks')]); renderBoard(); }
function showApplication() { const user = sessionUser(); document.getElementById('login-screen').classList.add('hidden'); document.querySelector('.app-shell').classList.remove('locked'); if (user) { document.getElementById('user-avatar').textContent = user.nome.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase(); } }
function showLogin() { sessionStorage.removeItem('fluxo_user'); document.getElementById('login-screen').classList.remove('hidden'); document.querySelector('.app-shell').classList.add('locked'); document.getElementById('login-form').reset(); }
document.getElementById('login-form').addEventListener('submit', async event => { event.preventDefault(); try { const user = await request('/api/login', { method: 'POST', body: JSON.stringify({ email: document.getElementById('login-email').value, password: document.getElementById('login-password').value }) }); sessionStorage.setItem('fluxo_user', JSON.stringify(user)); showApplication(); await loadData(); } catch (error) { handleError(error); } });
document.getElementById('signup-form').addEventListener('submit', async event => { event.preventDefault(); try { const user = await request('/api/users', { method: 'POST', body: JSON.stringify({ name: document.getElementById('signup-name').value.trim(), email: document.getElementById('signup-email').value.trim(), password: document.getElementById('signup-password').value }) }); sessionStorage.setItem('fluxo_user', JSON.stringify(user)); showApplication(); await loadData(); showToast('Conta criada com sucesso'); } catch (error) { handleError(error); } });
document.getElementById('show-signup').addEventListener('click', () => { document.getElementById('login-panel').classList.add('hidden'); document.getElementById('signup-panel').classList.remove('hidden'); });
document.getElementById('show-login').addEventListener('click', () => { document.getElementById('signup-panel').classList.add('hidden'); document.getElementById('login-panel').classList.remove('hidden'); });
document.getElementById('logout-btn').addEventListener('click', showLogin);
document.addEventListener('click', async event => { const viewButton = event.target.closest('[data-view]'); if (viewButton) { if (viewButton.dataset.view === 'task-form') resetTaskForm(); switchView(viewButton.dataset.view); return; } const action = event.target.closest('[data-action]'); if (!action) return; const task = tasks.find(item => item.id === Number(action.dataset.id)); if (!task) return; try { if (action.dataset.action === 'edit') return editTask(task.id); if (action.dataset.action === 'delete') { if (!confirm('Deseja realmente excluir esta tarefa?')) return; await request(`/api/tasks/${task.id}`, { method: 'DELETE' }); showToast('Tarefa excluída com sucesso'); } if (action.dataset.action === 'update-status') { const selectedStatus = document.querySelector(`[data-status-id="${task.id}"]`).value; await request(`/api/tasks/${task.id}`, { method: 'PUT', body: JSON.stringify({ description: task.description, sector: task.sector, userId: task.userId, priority: task.priority, status: selectedStatus }) }); showToast('Status atualizado com sucesso'); } await loadData(); } catch (error) { handleError(error); } });
document.getElementById('task-form').addEventListener('submit', async event => { event.preventDefault(); const data = { description: document.getElementById('task-description').value.trim(), sector: document.getElementById('task-sector').value.trim(), userId: document.getElementById('task-user').value, priority: document.getElementById('task-priority').value, status: document.getElementById('task-status').value }; const wasEditing = Boolean(editingId); try { await request(wasEditing ? `/api/tasks/${editingId}` : '/api/tasks', { method: wasEditing ? 'PUT' : 'POST', body: JSON.stringify(data) }); resetTaskForm(); await loadData(); switchView('board'); showToast(wasEditing ? 'Tarefa atualizada com sucesso' : 'Cadastro concluído com sucesso'); } catch (error) { handleError(error); } });
document.getElementById('user-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/users', { method: 'POST', body: JSON.stringify({ name: document.getElementById('user-name').value.trim(), email: document.getElementById('user-email').value.trim() }) }); event.target.reset(); await loadData(); renderUsers(); showToast('Cadastro concluído com sucesso'); } catch (error) { handleError(error); } });
document.getElementById('search-input').addEventListener('input', renderBoard); document.getElementById('sector-filter').addEventListener('change', renderBoard); document.getElementById('refresh-btn').addEventListener('click', () => loadData().catch(handleError));
if (sessionUser()) { showApplication(); loadData().catch(handleError); } else { document.querySelector('.app-shell').classList.add('locked'); }
